credentials:
  usernames:
    attrition:
      password: '$2b$12$5Zqun2t.fYhmMX7e17VM7OoaD6ynHCH4pDCkiG7zs8F4ZWMF284l2'
      name: 'Employee Attrition Predictor'

cookie:
  expiry_days: 0
  key: 'some_signature_key'
  name: 'attrition_app_cookie'

