credentials:
  usernames:
    attrition:
      name: Employee Attrition User
      email: morteyandrews@gmail.com
      logged_in: False  
      password: '$2b$12$LDwH6Qj/MHgF7Tb/67lKQOWL.d/1YWi6ewW5ANprBM1RdGURQ7mvS'  
     
cookie:
  expiry_days: 0 
  key: 'some_signature_key' 
  name: 'attrition_app_cookie' 

